version: '3'

services:
  api-recomendacao:
    container_name: ${APP_NAME}_recomendacao
    build:
      context: ./api-recomendacoes
    ports:
      - ${RECOMENDACAO_PORT}:3001
    tty: true
    depends_on:
      - api-catalogo

  api-catalogo:
    container_name: ${APP_NAME}_catalogo
    build:
      context: ./api-catalogo
    ports:
      - ${CATALOGO_PORT}:3000
    tty: true
    depends_on:
      - db-script
      - cache-redis

  db-script:
    container_name: ${APP_NAME}_db-script
    build:
      context: ./db-script
    tty: true
    entrypoint: dockerize -wait tcp://db-mysql:3306 -timeout 40s yarn start
    depends_on:
      - db-mysql

  db-mysql:
    container_name: ${APP_NAME}_db
    image: mysql:${MYSQL_VERSION}
    ports:
      - ${MYSQL_PORT}:3306
    command: --innodb-use-native-aio=0
    environment:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    tty: true

  cache-redis:
    container_name: ${APP_NAME}_cache
    image: redis:${REDIS_VERSION}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./.docker/redis:/data
    tty: true
